CULTURE_THEMES = [
    {"key": "geographie",  "name": "Géographie",  "icon": "🌍", "description": "Pays, capitales et géographie mondiale",        "color": "from-blue-500 to-cyan-500"},
    {"key": "sport",       "name": "Sport",        "icon": "⚽", "description": "Champions, records et compétitions",             "color": "from-green-500 to-emerald-500"},
    {"key": "histoire",    "name": "Histoire",     "icon": "📜", "description": "Événements et personnages historiques",          "color": "from-amber-500 to-yellow-500"},
    {"key": "sciences",    "name": "Sciences",     "icon": "🔬", "description": "Physique, chimie et biologie",                  "color": "from-purple-500 to-violet-500"},
    {"key": "musique",     "name": "Musique",      "icon": "🎵", "description": "Genres, artistes et instruments",               "color": "from-pink-500 to-rose-500"},
    {"key": "cinema",      "name": "Cinéma",       "icon": "🎬", "description": "Films, acteurs et réalisateurs",                "color": "from-red-500 to-orange-500"},
    {"key": "art",         "name": "Art",          "icon": "🎨", "description": "Peinture, sculpture et mouvements artistiques", "color": "from-orange-500 to-amber-500"},
    {"key": "technologie", "name": "Technologie",  "icon": "💻", "description": "Innovation et monde numérique",                "color": "from-indigo-500 to-blue-500"},
    {"key": "gastronomie", "name": "Gastronomie",  "icon": "🍽️", "description": "Plats, épices et traditions culinaires",        "color": "from-yellow-500 to-lime-500"},
    {"key": "nature",      "name": "Nature",       "icon": "🌿", "description": "Animaux, plantes et écosystèmes",               "color": "from-emerald-500 to-teal-500"},
    {"key": "astronomie",  "name": "Astronomie",   "icon": "🌌", "description": "Étoiles, planètes et univers",                 "color": "from-slate-500 to-indigo-500"},
    {"key": "philosophie", "name": "Philosophie",  "icon": "🧠", "description": "Penseurs, concepts et doctrines",              "color": "from-violet-500 to-purple-500"},
]

CULTURE_QUESTIONS = {
    "geographie": [
        {"id": 1, "question": "Quelle est la capitale de l'Australie ?",
         "options": ["Sydney", "Melbourne", "Canberra", "Brisbane"], "correct": "Canberra",
         "explanation": "Canberra est la capitale fédérale d'Australie, construite spécialement à cet effet entre Sydney et Melbourne."},
        {"id": 2, "question": "Quel est le plus grand pays du monde par superficie ?",
         "options": ["Canada", "Chine", "États-Unis", "Russie"], "correct": "Russie",
         "explanation": "La Russie couvre environ 17,1 millions de km², soit presque deux fois la superficie du Canada."},
        {"id": 3, "question": "Quel fleuve traverse l'Égypte du sud au nord ?",
         "options": ["Amazone", "Niger", "Nil", "Congo"], "correct": "Nil",
         "explanation": "Le Nil est le principal fleuve d'Égypte et le plus long du monde avec environ 6 650 km."},
        {"id": 4, "question": "Quelle mer sépare l'Europe de l'Afrique à l'ouest ?",
         "options": ["Mer Rouge", "Mer Noire", "Mer Méditerranée", "Mer Caspienne"], "correct": "Mer Méditerranée",
         "explanation": "La Méditerranée sépare l'Europe du nord de l'Afrique au sud et est entourée de 3 continents."},
    ],
    "sport": [
        {"id": 1, "question": "Combien de fois le Brésil a-t-il remporté la Coupe du Monde de football ?",
         "options": ["3", "4", "5", "6"], "correct": "5",
         "explanation": "Le Brésil est la nation la plus titrée avec 5 Coupes du Monde (1958, 1962, 1970, 1994, 2002)."},
        {"id": 2, "question": "Qui détient le record du monde du 100m masculin ?",
         "options": ["Carl Lewis", "Usain Bolt", "Tyson Gay", "Asafa Powell"], "correct": "Usain Bolt",
         "explanation": "Usain Bolt a établi le record mondial en 9,58 secondes lors des Mondiaux de Berlin en 2009."},
        {"id": 3, "question": "Combien de joueurs composent une équipe de basketball sur le terrain ?",
         "options": ["4", "5", "6", "7"], "correct": "5",
         "explanation": "Le basketball se joue en 5 contre 5, avec des remplaçants sur le banc."},
        {"id": 4, "question": "Dans quel sport pratique-t-on le 'smash' ?",
         "options": ["Football", "Natation", "Cyclisme", "Tennis"], "correct": "Tennis",
         "explanation": "Le smash est un coup puissant vers le bas, caractéristique du tennis et du badminton."},
    ],
    "histoire": [
        {"id": 1, "question": "En quelle année a débuté la Première Guerre mondiale ?",
         "options": ["1912", "1914", "1916", "1918"], "correct": "1914",
         "explanation": "La Première Guerre mondiale a débuté en juillet 1914 suite à l'assassinat de l'archiduc François-Ferdinand."},
        {"id": 2, "question": "Qui était le premier président des États-Unis ?",
         "options": ["John Adams", "Thomas Jefferson", "George Washington", "Benjamin Franklin"], "correct": "George Washington",
         "explanation": "George Washington est devenu le premier président des États-Unis en 1789."},
        {"id": 3, "question": "Quelle révolution a eu lieu en France en 1789 ?",
         "options": ["Révolution industrielle", "Révolution française", "Révolution américaine", "Révolution bolchevique"], "correct": "Révolution française",
         "explanation": "La Révolution française (1789-1799) a renversé la monarchie et établi les principes de liberté, égalité, fraternité."},
        {"id": 4, "question": "Qui a découvert l'Amérique en 1492 ?",
         "options": ["Vasco de Gama", "Fernand de Magellan", "Christophe Colomb", "Amerigo Vespucci"], "correct": "Christophe Colomb",
         "explanation": "Christophe Colomb a atteint les Amériques le 12 octobre 1492, lors d'un voyage financé par la couronne espagnole."},
    ],
    "sciences": [
        {"id": 1, "question": "Quel est le symbole chimique de l'or ?",
         "options": ["Or", "Au", "Ag", "Fe"], "correct": "Au",
         "explanation": "Le symbole Au vient du latin 'Aurum', le nom latin de l'or."},
        {"id": 2, "question": "Combien d'os possède le corps humain adulte ?",
         "options": ["186", "206", "226", "256"], "correct": "206",
         "explanation": "Le squelette humain adulte est composé de 206 os. À la naissance, un bébé en possède environ 300 qui fusionnent avec la croissance."},
        {"id": 3, "question": "Quelle planète est surnommée la 'planète rouge' ?",
         "options": ["Vénus", "Jupiter", "Mars", "Mercure"], "correct": "Mars",
         "explanation": "Mars doit sa couleur rouge à l'oxyde de fer (rouille) présent à sa surface."},
        {"id": 4, "question": "Quelle est la vitesse de la lumière dans le vide ?",
         "options": ["300 000 km/s", "150 000 km/s", "450 000 km/s", "1 000 000 km/s"], "correct": "300 000 km/s",
         "explanation": "La vitesse de la lumière est d'environ 299 792 km/s, arrondie à 300 000 km/s."},
    ],
    "musique": [
        {"id": 1, "question": "Combien de cordes possède une guitare classique ?",
         "options": ["4", "5", "6", "7"], "correct": "6",
         "explanation": "La guitare classique possède 6 cordes accordées en Mi, La, Ré, Sol, Si, Mi."},
        {"id": 2, "question": "Quel compositeur était sourd mais continuait à composer ?",
         "options": ["Mozart", "Beethoven", "Bach", "Chopin"], "correct": "Beethoven",
         "explanation": "Beethoven a composé certaines de ses plus grandes œuvres, dont la 9ème symphonie, après avoir perdu l'ouïe."},
        {"id": 3, "question": "Quel pays est le berceau du jazz ?",
         "options": ["France", "Cuba", "États-Unis", "Jamaïque"], "correct": "États-Unis",
         "explanation": "Le jazz est né à la Nouvelle-Orléans au début du XXe siècle, issu du blues et du ragtime."},
        {"id": 4, "question": "Combien de touches possède un piano classique ?",
         "options": ["76", "82", "88", "94"], "correct": "88",
         "explanation": "Le piano standard possède 88 touches : 52 blanches et 36 noires, sur 7 octaves complètes et un peu plus."},
    ],
    "cinema": [
        {"id": 1, "question": "Qui a réalisé le film 'Titanic' (1997) ?",
         "options": ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Ridley Scott"], "correct": "James Cameron",
         "explanation": "James Cameron a réalisé Titanic (1997), film aux 11 Oscars et qui fut longtemps le plus rentable de l'histoire."},
        {"id": 2, "question": "Dans quel film entend-on la réplique 'Que la Force soit avec toi' ?",
         "options": ["Indiana Jones", "Star Wars", "Star Trek", "E.T."], "correct": "Star Wars",
         "explanation": "Cette réplique emblématique est tirée de la saga Star Wars, créée par George Lucas."},
        {"id": 3, "question": "Quel acteur joue Iron Man dans les films Marvel ?",
         "options": ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], "correct": "Robert Downey Jr.",
         "explanation": "Robert Downey Jr. incarne Tony Stark / Iron Man depuis le premier film en 2008."},
        {"id": 4, "question": "Quel film de Pixar met en scène un robot solitaire sur Terre ?",
         "options": ["Toy Story", "WALL-E", "Cars", "Brave"], "correct": "WALL-E",
         "explanation": "WALL-E (2008) suit un robot compacteur de déchets resté seul sur Terre après que l'humanité l'a quittée."},
    ],
    "art": [
        {"id": 1, "question": "Qui a peint la Joconde ?",
         "options": ["Michel-Ange", "Raphaël", "Léonard de Vinci", "Botticelli"], "correct": "Léonard de Vinci",
         "explanation": "La Joconde (Mona Lisa) a été peinte par Léonard de Vinci entre 1503 et 1519."},
        {"id": 2, "question": "Dans quel musée est exposée la Joconde ?",
         "options": ["Le Prado", "Le Louvre", "La National Gallery", "Les Offices"], "correct": "Le Louvre",
         "explanation": "La Joconde est exposée au Musée du Louvre à Paris depuis 1797."},
        {"id": 3, "question": "Quel artiste espagnol est célèbre pour ses œuvres cubistes ?",
         "options": ["Salvador Dalí", "Joan Miró", "Pablo Picasso", "Francisco Goya"], "correct": "Pablo Picasso",
         "explanation": "Pablo Picasso est l'un des fondateurs du cubisme avec Georges Braque dans les années 1900."},
        {"id": 4, "question": "Qui a peint 'La Nuit étoilée' ?",
         "options": ["Paul Gauguin", "Claude Monet", "Vincent van Gogh", "Paul Cézanne"], "correct": "Vincent van Gogh",
         "explanation": "La Nuit étoilée est une peinture de Vincent van Gogh réalisée en 1889, conservée au MoMA de New York."},
    ],
    "technologie": [
        {"id": 1, "question": "Qui a fondé Apple ?",
         "options": ["Bill Gates", "Steve Jobs", "Elon Musk", "Mark Zuckerberg"], "correct": "Steve Jobs",
         "explanation": "Apple a été fondée en 1976 par Steve Jobs, Steve Wozniak et Ronald Wayne."},
        {"id": 2, "question": "Quelle est la signification de 'WWW' dans une adresse web ?",
         "options": ["World Wide Web", "World Web Works", "Wide World Web", "Web World Wide"], "correct": "World Wide Web",
         "explanation": "WWW signifie World Wide Web, inventé par Tim Berners-Lee en 1989."},
        {"id": 3, "question": "Quel langage de programmation est principalement utilisé pour le web front-end ?",
         "options": ["Python", "Java", "JavaScript", "C++"], "correct": "JavaScript",
         "explanation": "JavaScript est le langage de programmation principal pour le développement web front-end."},
        {"id": 4, "question": "Que signifie 'HTML' ?",
         "options": ["HyperText Machine Language", "HyperText Markup Language", "High-Tech Modern Language", "HyperTool Markup Language"],
         "correct": "HyperText Markup Language",
         "explanation": "HTML (HyperText Markup Language) est le langage de balisage standard pour créer des pages web."},
    ],
    "gastronomie": [
        {"id": 1, "question": "De quel pays la pizza est-elle originaire ?",
         "options": ["France", "Espagne", "Grèce", "Italie"], "correct": "Italie",
         "explanation": "La pizza est originaire d'Italie, et plus particulièrement de Naples où la pizza Margherita a été créée."},
        {"id": 2, "question": "Quel fromage est utilisé dans un vrai tiramisu ?",
         "options": ["Ricotta", "Parmesan", "Mascarpone", "Gorgonzola"], "correct": "Mascarpone",
         "explanation": "Le tiramisu traditionnel se prépare avec du mascarpone, des biscuits boudoirs, du café et du cacao."},
        {"id": 3, "question": "Le sushi est un plat traditionnel de quel pays ?",
         "options": ["Chine", "Corée", "Vietnam", "Japon"], "correct": "Japon",
         "explanation": "Le sushi est un plat traditionnel japonais à base de riz vinaigré et de poisson frais."},
        {"id": 4, "question": "Quelle épice est la plus chère au monde à poids égal ?",
         "options": ["Cardamome", "Safran", "Vanille", "Cannelle"], "correct": "Safran",
         "explanation": "Le safran est l'épice la plus chère au monde, obtenu à partir des stigmates du crocus sativus."},
    ],
    "nature": [
        {"id": 1, "question": "Quel animal a le plus grand cœur ?",
         "options": ["Éléphant", "Baleine bleue", "Girafe", "Cachalot"], "correct": "Baleine bleue",
         "explanation": "La baleine bleue possède le plus grand cœur du règne animal, pesant environ 180 kg."},
        {"id": 2, "question": "Comment appelle-t-on le processus par lequel les plantes fabriquent leur nourriture ?",
         "options": ["Respiration", "Photosynthèse", "Fermentation", "Transpiration"], "correct": "Photosynthèse",
         "explanation": "La photosynthèse permet aux plantes de convertir la lumière solaire, l'eau et le CO2 en sucre et en oxygène."},
        {"id": 3, "question": "Quel arbre produit le gland ?",
         "options": ["Châtaignier", "Hêtre", "Chêne", "Aulne"], "correct": "Chêne",
         "explanation": "Le gland est le fruit du chêne. Il servait autrefois à nourrir les cochons en forêt."},
        {"id": 4, "question": "Combien d'espèces d'insectes existent environ sur Terre ?",
         "options": ["100 000", "500 000", "1 million", "Plus de 5 millions"], "correct": "Plus de 5 millions",
         "explanation": "On estime qu'il existe plus de 5 millions d'espèces d'insectes sur Terre, dont seulement 1 million est décrite."},
    ],
    "astronomie": [
        {"id": 1, "question": "Quelle est la planète la plus grande du système solaire ?",
         "options": ["Saturne", "Neptune", "Jupiter", "Uranus"], "correct": "Jupiter",
         "explanation": "Jupiter est la plus grande planète du système solaire, avec une masse plus de 300 fois celle de la Terre."},
        {"id": 2, "question": "Combien d'années-lumière mesure environ la Voie Lactée en diamètre ?",
         "options": ["10 000", "50 000", "100 000", "1 000 000"], "correct": "100 000",
         "explanation": "La Voie Lactée mesure environ 100 000 années-lumière de diamètre et contient plus de 200 milliards d'étoiles."},
        {"id": 3, "question": "Qu'est-ce qu'une année-lumière ?",
         "options": ["La durée de rotation de la Terre", "La distance parcourue par la lumière en un an", "La luminosité d'une étoile", "L'âge d'une constellation"],
         "correct": "La distance parcourue par la lumière en un an",
         "explanation": "Une année-lumière équivaut à environ 9 461 milliards de kilomètres."},
        {"id": 4, "question": "Quel est le nom de notre galaxie ?",
         "options": ["Andromède", "La Voie Lactée", "Le Grand Nuage de Magellan", "Triangulum"], "correct": "La Voie Lactée",
         "explanation": "Notre galaxie s'appelle la Voie Lactée. La galaxie spirale voisine la plus proche est Andromède."},
    ],
    "philosophie": [
        {"id": 1, "question": "Qui est l'auteur de la formule 'Je pense, donc je suis' ?",
         "options": ["Pascal", "Descartes", "Kant", "Rousseau"], "correct": "Descartes",
         "explanation": "'Cogito, ergo sum' est la formule célèbre de René Descartes dans son Discours de la méthode (1637)."},
        {"id": 2, "question": "Quelle est la méthode philosophique de Socrate consistant à 'accoucher' les esprits ?",
         "options": ["La dialectique", "La maïeutique", "Le syllogisme", "L'empirisme"], "correct": "La maïeutique",
         "explanation": "La maïeutique socratique consiste à faire accoucher les esprits de leurs connaissances par le questionnement."},
        {"id": 3, "question": "Qui a écrit 'L'Être et le Néant' ?",
         "options": ["Albert Camus", "Simone de Beauvoir", "Jean-Paul Sartre", "Maurice Merleau-Ponty"], "correct": "Jean-Paul Sartre",
         "explanation": "Jean-Paul Sartre a publié L'Être et le Néant en 1943, ouvrage fondateur de l'existentialisme phénoménologique."},
        {"id": 4, "question": "Quelle branche de la philosophie étudie la nature de la connaissance ?",
         "options": ["L'ontologie", "L'éthique", "L'épistémologie", "L'esthétique"], "correct": "L'épistémologie",
         "explanation": "L'épistémologie étudie la nature, les sources et les limites de la connaissance humaine."},
    ],
}
