# Generated by Django 6.0.4 on 2026-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacedrepetition',
            name='next_review',
            field=models.DateField(db_index=True),
        ),
    ]
