# Generated by Django 6.0.2 on 2026-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_result_mastery_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('qcm', 'QCM'), ('true_false', 'True/False'), ('mixed', 'Mixte')], max_length=20),
        ),
    ]
