# Generated by Django 6.0.2 on 2026-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countdown_seconds', models.PositiveIntegerField(default=30)),
                ('mp_num_questions', models.PositiveIntegerField(default=10)),
                ('mp_themes', models.JSONField(blank=True, default=list)),
                ('mp_types', models.JSONField(blank=True, default=list)),
                ('mp_difficulty', models.CharField(default='medium', max_length=10)),
                ('mp_end_condition', models.CharField(choices=[('best_score', 'Répondre à toutes les questions — meilleur score'), ('elimination', 'Élimination à la première mauvaise réponse seul')], default='best_score', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du jeu',
                'verbose_name_plural': 'Paramètres du jeu',
            },
        ),
    ]
