"""
Django settings for APIBoileau project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    """Charge les variables d'environnement depuis un fichier .env.

    Chaque ligne au format CLE=VALEUR est injectée dans os.environ
    (sans écraser une variable déjà définie grâce à setdefault).
    Les lignes vides et les commentaires (#) sont ignorés.
    """
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


# Chargement automatique du fichier .env situé à la racine du projet Django
load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-yptk3fk%ihq8cay99wl5zpx==aj7g3!a=&a#afdgt42flmh6au",
)

DEBUG = os.getenv("DEBUG", "true").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


# Application definition

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INSTALLED_APPS = [
    'daphne',  # serveur ASGI pour runserver (doit précéder staticfiles/admin)
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'users',
    'documents',
    'quizzes',
    'summaries',
    'analytics',
    'srs',
    'friends',
    'culture',
    'adminapi',
    'gamesounds',
    'gamesettings',
    'duel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'APIBoileau.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'APIBoileau.wsgi.application'

# ── Channels / WebSockets (multijoueur temps réel) ─────────────────────────────
ASGI_APPLICATION = 'APIBoileau.asgi.application'
# Dev : couche en mémoire (mono-process via runserver/daphne).
# Prod : remplacer par channels_redis (RedisChannelLayer).
_REDIS_URL = os.getenv("REDIS_URL", "")
CHANNEL_LAYERS = {
    "default": (
        {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_REDIS_URL]},
        }
        if _REDIS_URL
        else {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    )
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# La configuration provient EXCLUSIVEMENT de la variable DATABASE_URL (fichier back/.env).
# Deux moteurs sont supportés, choisis automatiquement selon le schéma de l'URL :
#   PostgreSQL : DATABASE_URL=postgres://user:password@host:port/dbname
#   MySQL      : DATABASE_URL=mysql://user:password@host:port/dbname
# dj-database-url interprète l'URL et sélectionne le backend Django approprié.
DATABASE_URL = os.getenv("DATABASE_URL", "")
if not DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL est manquant. Definissez-le dans back/.env, par exemple :\n"
        "  PostgreSQL : DATABASE_URL=postgres://postgres:azertyuiop@localhost:5433/Boileau_db\n"
        "  MySQL      : DATABASE_URL=mysql://root:motdepasse@localhost:3306/Boileau_db\n"
        "(Le pilote 'mysqlclient' doit etre installe pour utiliser une URL mysql://.)"
    )

DATABASES = {
    "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600),
}

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
    ),
    # Par défaut, toutes les vues exigent un utilisateur authentifié.
    # Les endpoints publics (inscription, connexion, tokens, config publique)
    # se désinscrivent explicitement via permission_classes = [AllowAny].
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ── Cookies JWT ───────────────────────────────────────────────────────────────
# Secure=True uniquement en production (HTTPS).
JWT_AUTH_COOKIE_SECURE = not DEBUG
# SameSite=Lax protège contre CSRF tout en autorisant les redirections OAuth.
JWT_AUTH_COOKIE_SAMESITE = "Lax"

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ── Configuration Gemini ───────────────────────────────────────────────────────
# Ces variables sont lues depuis le fichier .env (chargé par load_env_file).
# GEMINI_API_KEY     : clé d'authentification Google AI Studio (obligatoire).
# GEMINI_MODEL       : identifiant du modèle, SANS le préfixe "models/".
#                      gemini-1.5-flash est déprécié → gemini-2.0-flash.
# GEMINI_TIMEOUT_SECONDS : durée max d'attente d'une réponse HTTP Gemini.
# GEMINI_SOURCE_MAX_CHARS : longueur max du texte source envoyé dans le prompt.
# ── CORS ──────────────────────────────────────────────────────────────────────
# Autorise le frontend React (port 3000) à appeler l'API Django.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]
CORS_ALLOW_CREDENTIALS = True

# ── Gemini ────────────────────────────────────────────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
GEMINI_TIMEOUT_SECONDS = int(os.getenv("GEMINI_TIMEOUT_SECONDS", "45"))
GEMINI_SOURCE_MAX_CHARS = int(os.getenv("GEMINI_SOURCE_MAX_CHARS", "12000"))
# Mode simulation : renvoie de fausses données sans appeler l'API Gemini.
# Mettre GEMINI_MOCK_MODE=true dans .env pour économiser les crédits.
GEMINI_MOCK_MODE = os.getenv("GEMINI_MOCK_MODE", "false").lower() in ("true", "1", "yes")

# ── Email ─────────────────────────────────────────────────────────────────────
# En développement, les emails s'affichent dans la console.
# En production, configurer un backend SMTP via les variables d'environnement.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@boileau.app")

# ── Config publique frontend (exposée via /api/public-config/) ─────────────
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
ONESIGNAL_APP_ID = os.getenv("ONESIGNAL_APP_ID", "")
