# Generated by Django 6.0.2 on 2026-06-05 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenger_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='end_condition',
            field=models.CharField(choices=[('best_score', 'Meilleur score'), ('elimination', 'Élimination')], default='best_score', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='num_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='challenge',
            name='opponent_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
