# Generated by Django 6.0.4 on 2026-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_challenge_async_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='quiz_type',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='theme',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
    ]
