# Generated by Django 6.0.4 on 2026-06-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_remove_challenge_quiz_type_remove_challenge_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('challenge_received', 'Défi reçu'), ('challenge_refused', 'Défi refusé'), ('challenge_result', 'Résultat de défi'), ('feature_request', 'Demande de fonctionnalité'), ('feature_approved', 'Fonctionnalité activée'), ('feature_refused', 'Fonctionnalité refusée')], max_length=30),
        ),
    ]
