# Generated by Django 6.0.2 on 2026-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_populate_culturequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturequestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='culturequestion',
            name='type',
            field=models.CharField(choices=[('qcm', 'QCM'), ('true_false', 'Vrai/Faux')], db_index=True, default='qcm', max_length=20),
        ),
    ]
