# Generated by Django 6.0.2 on 2026-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('background_music', 'Musique de fond'), ('correct', 'Bonne réponse'), ('wrong', 'Mauvaise réponse'), ('win', 'Victoire'), ('lose', 'Défaite')], max_length=32, unique=True)),
                ('audio', models.FileField(upload_to='game_sounds/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
