# Generated by Django 6.0.2 on 2026-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='type',
            field=models.CharField(choices=[('brief', 'Brief'), ('medium', 'Medium'), ('detailed', 'Detailed')], max_length=20),
        ),
    ]
