# Generated by Django 6.0.4 on 2026-06-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_onesignal_player_id_user_reset_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
